sudo: required
language: go
go:
    - 1.9.4
services:
    - docker
before_script:
    - mv ../${PWD##*/} ../caravela
    - mv ../../Strabox ../../strabox
script:
    - make build
    - make test
after_success:
    # Login in the docker daemon
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - make docker-upload OS=linux
notifications:
    on_success: never
    on_failure: never
