sudo: required
language: go
go:
    - 1.9.4
services:
    - docker
before_script:
    - mv ../${PWD##*/} ../caravela
    - mv ../../Strabox ../../strabox
script:
    - make build
    - make test
after_success:
    - make docker-build OS=linux
notifications:
    on_success: never
    on_failure: never
