language: go
go:
    - 1.9
before_script:
    - mv ../../Strabox/${PWD##*/} ../../strabox/caravela
script:
    - make build
    - make test
after_success:
env:
    global:
notifications:
    on_success: never
    on_failure: never
